export const HeaderApp = 'Todo App'
export const TitleTextBox = 'Enter todo name'
export const PlaceholderTextBox = 'Enter todo name here'
export const Filter = 'Filter'
export const ToggleAll = 'Toggle All' 
export const All = 'All' 
export const Done = 'Done' 
export const Active = 'Active' 